# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7ba21b74b4828a02715b1d1b68d2b7578ef1e96d963ded677c7cdfccb9faffb5fe58e8e819999d60fda9fec1043302f0e7f66501ea788c5cd2cfe54de82f44

test:
  secret_key_base: 1c2dce1eaaba7d5709c5e48a27acc12e2678d999e1516317405962ad1c7391a5004d0575c3d5d3385eb9f85a967e7b26150d1fdd96fd90dc567732b187128834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
